### ISSUE TITLE
Flat shading with light reflection strength

### ISSUE THREAD

**Issue by oxysoft** [dsoft20/psx_retroshader#1]
Hi, first let me say that I grew up with the PSX so this project is really awesome and I am actually using your shaders in my game in development currently. I hope more people start using these because I love the aesthetic created by the PSX's technical limitations

 I noticed that you started adding some more features in the past days to make this suite even more complete and while playing Spyro recently, I noticed a cool effect that I think would be a great effect.

Watch the spinning talisman at 11:03 in this video https://www.youtube.com/watch?v=vpjrIzTXdo8
Notice that its golden surface appears highly reflective by using normals to have certain faces almost completely black while faces coming into view are almost completely white. I think adding some sort of reflection strength and whatnot could be a nice addition.

**Comment by dsoft20** [comment]
Hi, sorry for the late reply.
I have edited the reflective shader a little to obtain something similar to the talisman surface.

![test](https://cloud.githubusercontent.com/assets/8696770/16561139/e71addae-41f7-11e6-8b3b-4066c111c9cc.png)

The edited shader is here:
[psx-unlit-simple.txt](https://github.com/dsoft20/psx_retroshader/files/346314/psx-unlit-simple.txt)

You have to use a cubemap like this (maybe done better ;P)
![b](https://cloud.githubusercontent.com/assets/8696770/16561071/7e61870e-41f7-11e6-82d9-30e285af22a5.png)

**Comment by oxysoft** [comment]
Very nice! I'll have to find some uses for the cubemap shaders, could spice it up

here is a picture of my game!
![image](https://cloud.githubusercontent.com/assets/3945277/16572636/a03b7952-4238-11e6-9af8-68f2e5db8647.png)
