### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Sandwall** [dsoft20/psx_retroshader#8]
I'm not very good with shaders, and I'm not sure how to use this shader package at all. I tried using Graphics.Blit on a script attached to the camera and a material with the unlit shader on it. I also tried applying the shader to a material, and using a render texture for the screen, but that didn't help at all. I'm not so sure what shaders I need to use in order to get all of these effects. The effect I'm trying to go for is a pixelated screen, with the "jitter" effect as well, as well as textures on my models. I am using Unity Version 2018.3.5.

**Comment by CSumm** [comment]
I think a simple how-to would definitely help. I'd like to use this on a small project as well

**Comment by CorvidCoven** [comment]
It's basically a standard surface shader that you'd apply to a material. Unfortunately, it was made in Unity's old default non-scriptable render pipeline therefore making it incompatible with the HDRP and URP. You'll have to manually upgrade the shaders yourself.

Edit: it seems someone already has upgraded it!

Edit 2: They did not upgrade it for SRPs, just the default renderer unfortunately
